[package]
name = "server-shared"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
server-core = { path = "../core" }

axum = { workspace = true }
sea-orm = { workspace = true }
