[package]
name = "server-service"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
server-model = { path = "../model" }

async-trait = { workspace = true, default-features = false }
