[package]
name = "server-model"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
validator = { workspace = true, features = ["derive"] }
derive-new = { workspace = true }
